/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./views/**/*.ejs", "./public/**/*.html"],
  theme: {
    extend: {
      colors: {
        // ── Existing brand colors (kept for pages not yet redesigned) ──────
        primary: "#00113a",
        secondary: "#795900",

        // ── Shadi Amour redesign — Material 3 palette ───────────────────────
        "on-tertiary-fixed": "#390b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#501300",
        "inverse-primary": "#b3c5ff",
        "on-tertiary-fixed-variant": "#783018",
        "on-background": "#1a1b20",
        "surface-container-low": "#f4f3f9",
        "secondary-container": "#fcc340",
        "secondary-fixed-dim": "#f6be3b",
        "on-tertiary-container": "#d37758",
        "on-error": "#ffffff",
        "halal-green": "#2E7D32",
        "error-container": "#ffdad6",
        "on-surface-variant": "#444650",
        background: "#faf8ff",
        "surface-container-high": "#e9e7ee",
        "primary-fixed-dim": "#b3c5ff",
        "on-primary-fixed": "#00174a",
        "trust-blue": "#003399",
        "surface-dim": "#dad9e0",
        "surface-container-lowest": "#ffffff",
        tertiary: "#2d0700",
        outline: "#757682",
        "on-primary-fixed-variant": "#2a4386",
        "primary-fixed": "#dbe1ff",
        "surface-container": "#efedf3",
        "inverse-surface": "#2f3035",
        "secondary-fixed": "#ffdea0",
        "neutral-gray": "#F8F9FA",
        "on-primary-container": "#758dd5",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "primary-container": "#002366",
        "surface-bright": "#faf8ff",
        "tertiary-fixed-dim": "#ffb59e",
        "surface-container-highest": "#e3e2e8",
        "tertiary-fixed": "#ffdbd0",
        "surface-variant": "#e3e2e8",
        "on-surface": "#1a1b20",
        error: "#ba1a1a",
        "on-secondary-fixed": "#261900",
        "on-secondary-container": "#6f5100",
        "on-secondary-fixed-variant": "#5c4300",
        "inverse-on-surface": "#f1f0f6",
        "surface-tint": "#435b9f",
        "premium-gold": "#C5A059",
        surface: "#faf8ff",
        "on-error-container": "#93000a",
        "surface-white": "#FFFFFF",
        "outline-variant": "#c5c6d2",
      },
      borderRadius: {
        none: "0px",
        sm: "4px",
        DEFAULT: "0.25rem",
        md: "12px",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "24px",
        "3xl": "32px",
        full: "9999px",
        button: "8px",
      },
      fontFamily: {
        "label-md": ["Hanken Grotesk"],
        "headline-md": ["Manrope"],
        "display-lg": ["Manrope"],
        "display-lg-mobile": ["Manrope"],
        "body-md": ["Hanken Grotesk"],
        "body-lg": ["Hanken Grotesk"],
        "headline-lg": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "800" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
      spacing: {
        gutter: "24px",
        "section-padding": "80px",
        "margin-x": "32px",
        "element-gap": "16px",
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};
